#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make our folders and links
mkdir -p \
    /config/crontabs \
    /data

rm -rf /etc/rsnapshot.conf
ln -s /config/rsnapshot.conf /etc/rsnapshot.conf

# adjust default config
sed -i -E 's@^#cmd_cp		/bin/cp$@cmd_cp		/bin/cp@g' /etc/rsnapshot.conf.default
sed -i -E 's@^#cmd_ssh	/usr/bin/ssh$@cmd_ssh	/usr/bin/ssh@g' /etc/rsnapshot.conf.default
sed -i -E 's@^#cmd_du		/usr/bin/du$@cmd_du		/usr/bin/du@g' /etc/rsnapshot.conf.default
sed -i -E 's@^#cmd_rsnapshot_diff	/usr/local/bin/rsnapshot-diff$@cmd_rsnapshot_diff	/usr/bin/rsnapshot-diff@g' /etc/rsnapshot.conf.default
sed -i -E 's@^#logfile	/var/log/rsnapshot$@logfile	/config/rsnapshot.log@g' /etc/rsnapshot.conf.default
sed -i -E 's@^#link_dest	0$@link_dest	1@g' /etc/rsnapshot.conf.default
sed -i -E 's@^backup	/home/		localhost/$@backup	/data/		localhost/\n#backup	/home/		localhost/@g' /etc/rsnapshot.conf.default
sed -i -E 's@^backup	/etc/		localhost/$@#backup	/etc/		localhost/@g' /etc/rsnapshot.conf.default
sed -i -E 's@^backup	/usr/local/	localhost/$@#backup	/usr/local/	localhost/@g' /etc/rsnapshot.conf.default

# copy crontab and rsnapshot defaults if needed
if [[ ! -f /config/crontabs/root ]]; then
    cp /etc/crontabs/root /config/crontabs/
fi

if [[ ! -f /etc/rsnapshot.conf ]]; then
    cp /etc/rsnapshot.conf.default /config/rsnapshot.conf
fi

# import user crontabs
rm /etc/crontabs/*
cp /config/crontabs/* /etc/crontabs/

# permissions
lsiown -R abc:abc \
    /config
